(rule
   (targets ocaml_flint_core.ml ocaml_flint_core_stub.c)
   (action (run %{exe:generator/generator.exe}))
   (mode (promote (until-clean))))

(library
 (name flint)
 (public_name flint)
 (c_library_flags (:include ../configure/libs.sexp) "-lflint")
 (foreign_stubs
  (language c)
  (names ocaml_flint_utils ocaml_flint_core_stub)
  (flags
   (:include ../configure/c_flags.sexp)
   "-Werror=implicit-function-declaration" -std=gnu11 :standard)
  (include_dirs
   (lib zarith))
   (extra_deps "ocaml_flint_utils.h"))
 (libraries zarith threads)
 (flags -w -9-27)
)

(env (dev (c_flags -Wall -Werror -Wconversion -Wstrict-prototypes --pedantic-errors :standard )))